# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 0) do

  create_table "sqlite_sequence", :id => false, :force => true do |t|
    t.column "name", :float
    t.column "seq", :float
  end

  create_table "users", :force => true do |t|
    t.column "name", :string, :limit => 128, :null => false
    t.column "password", :string, :limit => 128, :null => false
  end

end
